#mybatis:
#  mapper-locations: classpath*:mapper/*.xml
#  type-aliases-package: com.tr1912.ssmspringboot.springboottest.domain

#mybatis-plus的配置
mybatis-plus:
  type-aliases-package: com.haier.textparsing.pojo
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8088

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root